title: Changbai Mountain Guandonglv International Travel
name: Changbai Mountain Guandonglv International Travel
description: Licensed & Insured Inbound Tours to Changbai Mountain
url: "https://www.changbaishan-tour.space"
baseurl: ""
remote_theme: mmistakes/minimal-mistakes@4.24.0

# Multilingual support
languages:
  - en
  - ko
  - ja
default_lang: en

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap